### PR TITLE
Improve signal handling

### PR DESCRIPTION
**Pull request by dhellmann**
Improve the way we deal with signals that might interrupt processing,
and clean up some of our shutdown logic at the same time.

### CODE REVIEW

**Comment by ryanpetrello** [comment]
I'm assuming you've tested this against devstack?  I don't see any tests in this pull request.

**Comment by dhellmann** [comment]
I've tested this with devstack with the signals listed in the new daemon module. I've also added one more changeset to improve the ctrl-c handling.

**Comment by dhellmann** [comment]
And the last update makes it pass the brand new shiny pep8 with additional arbitrary rules.

**Comment by ryanpetrello** [comment]
Yea, I was wondering about pep8.  Looks like a ton of shit is failing on OpenStack CI because of it.  -_-

**Pull request merged**
